groups:
  md_5:
  - admin
disabled_commands:
- disabledcommandhere
timeout: 30000
online_mode: true
reject_transfers: false
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
stats: b5803973-db4c-408e-af0c-d661824f5852
network_compression_threshold: 256
log_pings: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
ip_forward: false
player_limit: -1
log_commands: false
connection_throttle_limit: 3
connection_throttle: 4000
enforce_secure_profile: false
prevent_proxy_connections: false
remote_ping_timeout: 5000
forge_support: false
remote_ping_cache: -1
max_packets_per_second: 4096
max_packets_data_per_second: 33554432
